# 
#   _config.yml
# 

title : 立命館大学 物理科学研究会 公式HP
author: 立命館大学物理科学研究会
email : vuccaken@gmail.com
keywords: 立命館大学, 物理科学研究会
description: >- # this means to ignore newlines until "baseurl:"
  Now developing......
baseurl: "/" # the subpath of your site, e.g. /blog
url    : "http://vuccaken.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vuccaken
github_username : vuccaken

highlighter: rouge # code syntax highlight

collections:
  members:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true
  # - scope:
  #     path: ""
  #     type: "pages"
  #   values:
  #     toc: false

