title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Now developing......
baseurl: "/new-hp" # the subpath of your site, e.g. /blog
url: "http://vuccaken.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vuccaken
github_username:  vuccaken

collections:
  members:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true

